name: namer_app
description: A new Flutter project.
publish_to: "none"
version: 0.0.1+1
environment:
  sdk: ">=3.0.6 <4.0.0"
dependencies:
  cupertino_icons: ^1.0.2
  english_words: ^4.0.0
  flutter:
    sdk: flutter
  provider: ^6.0.5
dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
flutter:
  uses-material-design: true
